"""enforce name+version unique constraint

Revision ID: 3a7a5ae313c5
Revises: 99e71c38ba40
Create Date: 2025-05-21 03:14:30.731821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7a5ae313c5'
down_revision: Union[str, None] = '99e71c38ba40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prompt_name_version', 'prompts', ['name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompt_name_version', 'prompts', type_='unique')
    # ### end Alembic commands ###
