"""enforce name+version unique constraint

Revision ID: 9494dc85998d
Revises: 3a7a5ae313c5
Create Date: 2025-05-21 03:17:06.984013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9494dc85998d'
down_revision: Union[str, None] = '3a7a5ae313c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompts_name', table_name='prompts')
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.create_index('ix_prompts_name', 'prompts', ['name'], unique=True)
    # ### end Alembic commands ###
