"""add body column to prompts

Revision ID: 99e71c38ba40
Revises: f692a40e8d55
Create Date: 2025-05-21 02:14:05.161718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e71c38ba40'
down_revision: Union[str, None] = 'f692a40e8d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('body', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'body')
    # ### end Alembic commands ###
